# Generated by Django 2.2.6 on 2019-10-25 13:01

from django.db import migrations, models
import projects.models
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('internal_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image_icon', models.FileField(blank=True, null=True, upload_to=projects.models.tech_used_upload)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Technologies Used',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('internal_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('featured', models.BooleanField(default=False)),
                ('project_client', models.CharField(blank=True, max_length=100, null=True)),
                ('project_type', models.CharField(blank=True, max_length=120, null=True)),
                ('description', tinymce.models.HTMLField(verbose_name='Content')),
                ('related_article', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to=projects.models.project_upload)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to=projects.models.project_upload)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to=projects.models.project_upload)),
                ('image_3', models.ImageField(blank=True, null=True, upload_to=projects.models.project_upload)),
                ('image_4', models.ImageField(blank=True, null=True, upload_to=projects.models.project_upload)),
                ('category', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('technologies_used', models.ManyToManyField(blank=True, to='projects.Technology')),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ['-updated', 'date_created'],
            },
        ),
    ]
